version: '3.8'

services:
  xtreamium-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - XTREAMIUM_BACKEND_PORT=8000
      - DATABASE_URL=postgresql://xtreamium:password@postgres:5432/xtreamium
      # Remove SSL for local development
      - DISABLE_SSL=true
    volumes:
      # Mount data directory for SQLite (if using SQLite instead of PostgreSQL)
      - ./data:/app/data
      # Mount SSL certificates (uncomment if using SSL)
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=xtreamium
      - POSTGRES_USER=xtreamium
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: