"""Initial migration

Revision ID: 1cec460a3478
Revises: 
Create Date: 2025-09-17 17:59:12.625143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cec460a3478'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('channels', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('channels', 'xmltv_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_channels_server_id'), table_name='channels')
    op.drop_index(op.f('idx_channels_user_id'), table_name='channels')
    op.drop_index(op.f('idx_channels_user_server'), table_name='channels')
    op.drop_index(op.f('idx_channels_xmltv_id'), table_name='channels')
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_xmltv_id'), 'channels', ['xmltv_id'], unique=False)
    op.create_unique_constraint('uq_channel_user_server_xmltv', 'channels', ['user_id', 'server_id', 'xmltv_id'])
    op.alter_column('epg', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('idx_epg_last_updated'), table_name='epg')
    op.drop_index(op.f('idx_epg_server_id'), table_name='epg')
    op.drop_index(op.f('idx_epg_user_id'), table_name='epg')
    op.alter_column('programmes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('programmes', 'start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('programmes', 'stop_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('programmes', 'pdc_start',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('programmes', 'vps_start',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('programmes', 'showview',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('programmes', 'videoplus',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('programmes', 'clumpidx',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'0/1'"))
    op.alter_column('programmes', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_programmes_id'), 'programmes', ['id'], unique=False)
    op.create_index(op.f('ix_programmes_start_time'), 'programmes', ['start_time'], unique=False)
    op.create_index(op.f('ix_programmes_stop_time'), 'programmes', ['stop_time'], unique=False)
    op.alter_column('servers', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('servers', 'owner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('servers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('servers', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('servers', 'epg_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_servers_id'), table_name='servers')
    op.drop_index(op.f('idx_servers_name'), table_name='servers')
    op.drop_index(op.f('idx_servers_owner_id'), table_name='servers')
    op.create_index(op.f('ix_servers_epg_url'), 'servers', ['epg_url'], unique=False)
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_index(op.f('ix_servers_password'), 'servers', ['password'], unique=False)
    op.create_index(op.f('ix_servers_url'), 'servers', ['url'], unique=False)
    op.create_index(op.f('ix_servers_username'), 'servers', ['username'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_servers_username'), table_name='servers')
    op.drop_index(op.f('ix_servers_url'), table_name='servers')
    op.drop_index(op.f('ix_servers_password'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_epg_url'), table_name='servers')
    op.create_index(op.f('idx_servers_owner_id'), 'servers', ['owner_id'], unique=False)
    op.create_index(op.f('idx_servers_name'), 'servers', ['name'], unique=False)
    op.create_index(op.f('idx_servers_id'), 'servers', ['id'], unique=False)
    op.alter_column('servers', 'epg_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('servers', 'owner_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('servers', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_programmes_stop_time'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_start_time'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_id'), table_name='programmes')
    op.alter_column('programmes', 'date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'clumpidx',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0/1'"))
    op.alter_column('programmes', 'videoplus',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'showview',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'vps_start',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'pdc_start',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'stop_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('programmes', 'start_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('programmes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_epg_user_id'), 'epg', ['user_id'], unique=False)
    op.create_index(op.f('idx_epg_server_id'), 'epg', ['server_id'], unique=False)
    op.create_index(op.f('idx_epg_last_updated'), 'epg', ['last_updated'], unique=False)
    op.alter_column('epg', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_channel_user_server_xmltv', 'channels', type_='unique')
    op.drop_index(op.f('ix_channels_xmltv_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.create_index(op.f('idx_channels_xmltv_id'), 'channels', ['xmltv_id'], unique=False)
    op.create_index(op.f('idx_channels_user_server'), 'channels', ['user_id', 'server_id'], unique=False)
    op.create_index(op.f('idx_channels_user_id'), 'channels', ['user_id'], unique=False)
    op.create_index(op.f('idx_channels_server_id'), 'channels', ['server_id'], unique=False)
    op.alter_column('channels', 'xmltv_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('channels', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('channels', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
