"""Initial

Revision ID: 7d9878e5bfbd
Revises: 
Create Date: 2025-09-26 19:12:24.541421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9878e5bfbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('epg_url', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_epg_url'), 'servers', ['epg_url'], unique=False)
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_index(op.f('ix_servers_password'), 'servers', ['password'], unique=False)
    op.create_index(op.f('ix_servers_url'), 'servers', ['url'], unique=False)
    op.create_index(op.f('ix_servers_username'), 'servers', ['username'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('xmltv_id', sa.String(), nullable=False),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.Column('icons', sa.Text(), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'server_id', 'xmltv_id', name='uq_channel_user_server_xmltv')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_xmltv_id'), 'channels', ['xmltv_id'], unique=False)
    op.create_table('epg',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('programs_data', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('program_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_id')
    )
    op.create_table('programmes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('stop_time', sa.String(), nullable=True),
    sa.Column('pdc_start', sa.String(), nullable=True),
    sa.Column('vps_start', sa.String(), nullable=True),
    sa.Column('showview', sa.String(), nullable=True),
    sa.Column('videoplus', sa.String(), nullable=True),
    sa.Column('clumpidx', sa.String(), nullable=True),
    sa.Column('titles', sa.Text(), nullable=True),
    sa.Column('sub_titles', sa.Text(), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('credits', sa.Text(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('orig_language', sa.Text(), nullable=True),
    sa.Column('length', sa.Text(), nullable=True),
    sa.Column('icons', sa.Text(), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('episode_nums', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('audio', sa.Text(), nullable=True),
    sa.Column('previously_shown', sa.Text(), nullable=True),
    sa.Column('premiere', sa.Text(), nullable=True),
    sa.Column('last_chance', sa.Text(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.Column('subtitles', sa.Text(), nullable=True),
    sa.Column('ratings', sa.Text(), nullable=True),
    sa.Column('star_ratings', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_programme_channel_start', 'programmes', ['channel_id', 'start_time'], unique=False)
    op.create_index('idx_programme_start_stop', 'programmes', ['start_time', 'stop_time'], unique=False)
    op.create_index(op.f('ix_programmes_id'), 'programmes', ['id'], unique=False)
    op.create_index(op.f('ix_programmes_start_time'), 'programmes', ['start_time'], unique=False)
    op.create_index(op.f('ix_programmes_stop_time'), 'programmes', ['stop_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programmes_stop_time'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_start_time'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_id'), table_name='programmes')
    op.drop_index('idx_programme_start_stop', table_name='programmes')
    op.drop_index('idx_programme_channel_start', table_name='programmes')
    op.drop_table('programmes')
    op.drop_table('epg')
    op.drop_index(op.f('ix_channels_xmltv_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_servers_username'), table_name='servers')
    op.drop_index(op.f('ix_servers_url'), table_name='servers')
    op.drop_index(op.f('ix_servers_password'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_epg_url'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
